---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: "add php support for apache"
    apt:
      name: libapache2-mod-php
      state: absent
